
CREATE DATABASE IF NOT EXISTS port;
CREATE DATABASE IF NOT EXISTS serv;
CREATE DATABASE IF NOT EXISTS keycloak;
CREATE DATABASE IF NOT EXISTS digital_exchange;
CREATE DATABASE IF NOT EXISTS t1;
CREATE DATABASE IF NOT EXISTS t2;
CREATE DATABASE IF NOT EXISTS t3;
